spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgrespass

  security:
    enabled: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true
token:
  secret: IUJSJWMveG5bdjNBdjk7cg==
  expiration: 600000
logging:
  level:
    org:
      hibernate:
        type: TRACE