spring:
  flyway:
    ignore-missing-migrations: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true
#  security:
#    user:
#      name: user1
logging:
  level:
    org:
      hibernate:
        type: TRACE

jwt:
  header: Authorization
  secret: reck
  expiration: 900000000